name: Selenium Tests with Allure

on:
  push:
    branches:
      - pipeline


jobs:
  selenium-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests with Allure
        run: mvn test

      - name: List Allure Results Directory
        run: ls -l allure-results || ls -l target/allure-results

      - name: Install Allure Commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip
          sudo unzip allure.zip -d /opt/
          sudo ln -s /opt/allure-2.19.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report || allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: allure-report/
